#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#define AUDIO_INPUT_SAMPLE_RATE  16000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

#define AUDIO_I2S_MIC_GPIO_WS   GPIO_NUM_7
#define AUDIO_I2S_MIC_GPIO_SCK  GPIO_NUM_6
#define AUDIO_I2S_MIC_GPIO_DIN  GPIO_NUM_5

#define AUDIO_I2S_SPK_GPIO_DOUT GPIO_NUM_2
#define AUDIO_I2S_SPK_GPIO_BCLK GPIO_NUM_3
#define AUDIO_I2S_SPK_GPIO_LRCK GPIO_NUM_4

#define TOUCH_BUTTON_GPIO       GPIO_NUM_0

#define TOUCH_BUTTON_ACTIVE_HIGH -1

#define LIGHT_STRIP_GPIO        GPIO_NUM_0
#define LED_NUM                 4

#define LEFT_BACK_LEG_PIN    GPIO_NUM_20
#define RIGHT_BACK_LEG_PIN   GPIO_NUM_21
#define LEFT_FRONT_LEG_PIN   GPIO_NUM_1
#define RIGHT_FRONT_LEG_PIN  GPIO_NUM_10

#define DISPLAY_SDA_PIN GPIO_NUM_8
#define DISPLAY_SCL_PIN GPIO_NUM_9
#define DISPLAY_WIDTH   128
#define DISPLAY_HEIGHT  64

#define DISPLAY_MIRROR_X true
#define DISPLAY_MIRROR_Y true

#define LAMP_GPIO GPIO_NUM_NC

#endif
